name: Sync Dependabot Bump
on:
  pull_request:
    branches: dependabot/npm_and_yarn/**

jobs:
  sync:
    name: Sync dependency files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Sync Script
        run: node ./scripts/sync-dependencies.mjs {{github.ref_name}}
      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bumped {{github.ref_name}} changes in config/dependencies.yaml"
          git push
